import logging
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
from PIL import Image
import os
import json

logging.basicConfig(level=logging.INFO)

TOKEN = '7260647302:AAExw2yeMZ9F4BmxA1rzrL0v-4YishFAh3Y'  # Replace with your actual bot token

# Configuration
CONFIG = {
    "image_width": 1024,
        "image_height": 1024,
            "image_quality": 95,
                "total_nfts": 1,
                }

                # Traits and layers paths
                TRAITS_PATHS = {}

                # Layer management
                LAYERS = {}

                def start(update, context):
                    context.bot.send_message(chat_id=update.effective_chat.id, text='Welcome to Pawart_bot!')
                        context.bot.send_message(chat_id=update.effective_chat.id, text='Please configure the NFT generation:')
                            context.bot.send_message(chat_id=update.effective_chat.id, text='Type /resolution <width> <height> to change the resolution')
                                context.bot.send_message(chat_id=update.effective_chat.id, text='Type /total <number> to change the number of NFTs to generate')
                                    context.bot.send_message(chat_id=update.effective_chat.id, text='Type /upload to upload the background layer')
                                        context.bot.send_message(chat_id=update.effective_chat.id, text='Type /layers to manage your layers')

                                        def resolution(update, context):
                                            try:
                                                    width, height = map(int, context.args)
                                                            CONFIG["image_width"] = width
                                                                    CONFIG["image_height"] = height
                                                                            context.bot.send_message(chat_id=update.effective_chat.id, text=f'Resolution set to {width}x{height}')
                                                                                except ValueError:
                                                                                        context.bot.send_message(chat_id=update.effective_chat.id, text='Invalid resolution format. Please use /resolution <width> <height>')

                                                                                        def total_nfts(update, context):
                                                                                            try:
                                                                                                    total = int(context.args[0])
                                                                                                            CONFIG["total_nfts"] = total
                                                                                                                    context.bot.send_message(chat_id=update.effective_chat.id, text=f'Total NFTs set to {total}')
                                                                                                                        except ValueError:
                                                                                                                                context.bot.send_message(chat_id=update.effective_chat.id, text='Invalid total NFTs format. Please use /total <number>')

                                                                                                                                def upload_layer(update, context):
                                                                                                                                    context.bot.send_message(chat_id=update.effective_chat.id, text='Please upload the background layer')

                                                                                                                                    def upload(update, context):
                                                                                                                                        file_id = update.message.document.file_id
                                                                                                                                            file = context.bot.get_file(file_id)
                                                                                                                                                file.download('layer.png')
                                                                                                                                                    TRAITS_PATHS['Background'] = 'layer.png'
                                                                                                                                                        LAYERS['Background'] = 'layer.png'
                                                                                                                                                            context.bot.send_message(chat_id=update.effective_chat.id, text='Layer uploaded successfully!')

                                                                                                                                                            def layers(update, context):
                                                                                                                                                                context.bot.send_message(chat_id=update.effective_chat.id, text='Your layers:')
                                                                                                                                                                    for layer, file_name in LAYERS.items():
                                                                                                                                                                            context.bot.send_message(chat_id=update.effective_chat.id, text=f'{layer}: {file_name}')

                                                                                                                                                                            def delete_layer(update, context):
                                                                                                                                                                                try:
                                                                                                                                                                                        layer_name = context.args[0]
                                                                                                                                                                                                if layer_name in LAYERS:
                                                                                                                                                                                                            del LAYERS[layer_name]
                                                                                                                                                                                                                        context.bot.send_message(chat_id=update.effective_chat.id, text=f'Layer {layer_name} deleted successfully!')
                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                            context.bot.send_message(chat_id=update.effective_chat.id, text=f'Layer {layer_name} not found!')
                                                                                                                                                                                                                                                except IndexError:
                                                                                                                                                                                                                                                        context.bot.send_message(chat_id=update.effective_chat.id, text='Please specify the layer name!')

                                                                                                                                                                                                                                                        def rename_layer(update, context):
                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                    old_name, new_name = context.args
                                                                                                                                                                                                                                                                            if old_name in LAYERS:
                                                                                                                                                                                                                                                                                        LAYERS[new_name] = LAYERS.pop(old_name)
                                                                                                                                                                                                                                                                                                    context.bot.send_message(chat_id=update.effective_chat.id, text=f'Layer {old_name} renamed to {new_name} successfully!')
                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                        context.bot.send_message(chat_id=update.effective_chat.id, text=f'Layer {old_name} not found!')
                                                                                                                                                                                                                                                                                                                            except IndexError:
                                                                                                                                                                                                                                                                                                                                    context.bot.send_message(chat_id=update.effective_chat.id, text='Please specify the old and new layer names!')

                                                                                                                                                                                                                                                                                                                                    def generate_nft(update, context):
                                                                                                                                                                                                                                                                                                                                        for _ in range(CONFIG["total_nfts"]):
                                                                                                                                                                                                                                                                                                                                                # Generate a random combination of traits
                                                                                                                                                                                                                                                                                                                                                        traits_combination = TRAITS_PATHS

                                                                                                                                                                                                                                                                                                                                                                # Create image
                                                                                                                                                                                                                                                                                                                                                                        layers = []
                                                                                                                                                                                                                                                                                                                                                                                for trait, file_name in traits_combination.items():
                                                                                                                                                                                                                                                                                                                                                                                            image_path = file_name
                                                                                                                                                                                                                                                                                                                                                                                                        layer = Image.open(image_path).convert("RGBA")
                                                                                                                                                                                                                                                                                                                                                                                                                    layer = layer.resize((CONFIG["image_width"], CONFIG["image_height"]))
                                                                                                                                                                                                                                                                                                                                                                                                                                layers.append(layer)

                                                                                                                                                                                                                                                                                                                                                                                                                                        base = Image.new("RGBA", (CONFIG["image_width"], CONFIG["image_height"]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                for layer in layers:
                                                                                                                                                                                                                                                                                                                                                                                                                                                              base = Image.alpha_composite(base, layer)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      output_path = f"nft_{_ + 1}.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              base.save(output_path, quality=CONFIG["image_quality"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # Create metadata
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              metadata = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "name": f"NFT #{_ + 1}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "description": "An awesome NFT collection!",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "image": output_path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "attributes": [{"trait_type": trait, "value": file_name.split('.')[0]} for trait, file_name in traits_combination.items()],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Save metadata to individual files
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      with open(f"metadata_{_ + 1}.json", 'w') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  json.dump(metadata, f, indent=4)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      context.bot.send_message(chat_id=update.effective_chat.id, text=f"Generated {CONFIG['total_nfts']} NFTs successfully!")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          updater = Updater(TOKEN, use_context=True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dp = updater.dispatcher

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dp.add_handler(CommandHandler('start', start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      dp.add_handler(CommandHandler('resolution', resolution))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          dp.add_handler(CommandHandler('total', total_nfts))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dp.add_handler(CommandHandler('upload', upload_layer))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dp.add_handler(MessageHandler(Filters.document, upload))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      dp.add_handler(CommandHandler('layers', layers))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          dp.add_handler(CommandHandler('delete', delete_layer))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dp.add_handler(CommandHandler('rename', rename_layer))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dp.add_handler(CommandHandler('generate', generate_nft))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updater.start_polling()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          updater.idle()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              main() 